const U={w:{p:'♙',n:'♘',b:'♗',r:'♖',q:'♕',k:'♔'},b:{p:'♟',n:'♞',b:'♝',r:'♜',q:'♛',k:'♚'}};const files='abcdefgh';let S,undo=[],flipped=false,promotionMove=null;
function initial(){let b=Array.from({length:8},()=>Array(8).fill(null));const back=['r','n','b','q','k','b','n','r'];for(let c=0;c<8;c++){b[0][c]={c:'b',t:back[c]};b[1][c]={c:'b',t:'p'};b[6][c]={c:'w',t:'p'};b[7][c]={c:'w',t:back[c]}}return{b,turn:'w',cast:{w:{k:true,q:true},b:{k:true,q:true}},ep:null,selected:null,moves:[],history:[],captured:{w:[],b:[]},over:null,positions:{}}}
function clone(x){return JSON.parse(JSON.stringify(x))}function inside(r,c){return r>=0&&r<8&&c>=0&&c<8}function enemy(c){return c==='w'?'b':'w'}function key(b){return b.map(r=>r.map(p=>p?p.c+p.t:'.').join('')).join('/')}
function setup(){S=initial();S.positions[key(S.b)]=1;undo=[];render()}function pieceAt(b,r,c){return inside(r,c)?b[r][c]:null}
function attacks(b,r,c,by){for(let y=0;y<8;y++)for(let x=0;x<8;x++){let p=b[y][x];if(!p||p.c!==by)continue;let dr=r-y,dc=c-x;if(p.t==='p'&&dr===(by==='w'?-1:1)&&Math.abs(dc)===1)return true;if(p.t==='n'&&[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].some(a=>a[0]===dr&&a[1]===dc))return true;if(p.t==='k'&&Math.max(Math.abs(dr),Math.abs(dc))===1)return true;let diag=Math.abs(dr)===Math.abs(dc),straight=dr===0||dc===0,slider=(p.t==='b'&&diag)||(p.t==='r'&&straight)||(p.t==='q'&&(diag||straight));if(slider){let sr=Math.sign(dr),sc=Math.sign(dc),rr=y+sr,cc=x+sc,clear=true;while(rr!==r||cc!==c){if(b[rr][cc])clear=false;rr+=sr;cc+=sc}if(clear)return true}}return false}
function king(b,c){for(let r=0;r<8;r++)for(let x=0;x<8;x++)if(b[r][x]?.c===c&&b[r][x].t==='k')return{r,c:x};return null}function inCheck(b,c){let k=king(b,c);return k?attacks(b,k.r,k.c,enemy(c)):true}
function pseudo(r,c){let p=S.b[r][c],out=[],add=(rr,cc,extra={})=>{if(!inside(rr,cc))return;let q=S.b[rr][cc];if(!q||q.c!==p.c)out.push({from:{r,c},to:{r:rr,c:cc},piece:{...p},capture:q?{...q}:null,...extra})};if(p.t==='p'){let d=p.c==='w'?-1:1;if(inside(r+d,c)&&!S.b[r+d][c]){add(r+d,c,{promotion:r+d===0||r+d===7});if((p.c==='w'?r===6:r===1)&&!S.b[r+2*d][c])add(r+2*d,c,{double:true})}for(let dc of[-1,1]){let rr=r+d,cc=c+dc;if(!inside(rr,cc))continue;if(S.b[rr][cc]?.c!==p.c&&S.b[rr][cc])add(rr,cc,{promotion:rr===0||rr===7});if(S.ep&&S.ep.r===rr&&S.ep.c===cc)add(rr,cc,{ep:true,capture:{c:enemy(p.c),t:'p'}})}}if(p.t==='n'){for(let a of[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+a[0],c+a[1])}if('brq'.includes(p.t)){let ds=[];if('bq'.includes(p.t))ds.push([1,1],[1,-1],[-1,1],[-1,-1]);if('rq'.includes(p.t))ds.push([1,0],[-1,0],[0,1],[0,-1]);for(let d of ds){let rr=r+d[0],cc=c+d[1];while(inside(rr,cc)){let q=S.b[rr][cc];if(q){if(q.c!==p.c)add(rr,cc);break}add(rr,cc);rr+=d[0];cc+=d[1]}}}if(p.t==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);let home=p.c==='w'?7:0,rights=S.cast[p.c];if(r===home&&c===4&&!inCheck(S.b,p.c)){for(let side of['k','q']){let rookCol=side==='k'?7:0,pass=side==='k'?[5,6]:[3,2];if(rights[side]&&S.b[home][rookCol]?.t==='r'&&!S.b[home][pass[0]]&&!S.b[home][pass[1]]&&!attacks(S.b,home,pass[0],enemy(p.c))&&!attacks(S.b,home,pass[1],enemy(p.c)))add(home,side==='k'?6:2,{castle:side})}}}return out}
function apply(b,m){let n=b.map(r=>r.map(p=>p&&{...p})),p=n[m.from.r][m.from.c];n[m.from.r][m.from.c]=null;if(m.ep)n[m.from.r][m.to.c]=null;if(m.castle){let rc=m.castle==='k'?7:0,tc=m.castle==='k'?5:3;n[m.from.r][tc]=n[m.from.r][rc];n[m.from.r][rc]=null}n[m.to.r][m.to.c]={...p,t:m.promote||p.t};return n}
function legal(r,c){let p=S.b[r][c];return pseudo(r,c).filter(m=>!inCheck(apply(S.b,m),p.c))}
function allLegal(c){let a=[];for(let r=0;r<8;r++)for(let x=0;x<8;x++)if(S.b[r][x]?.c===c)a.push(...legal(r,x));return a}
function select(r,c){S.selected={r,c};S.moves=legal(r,c);render()}
function click(r,c){if(S.over||promotionMove)return;let p=S.b[r][c];if(S.selected){let m=S.moves.find(x=>x.to.r===r&&x.to.c===c);if(m){if(m.promotion){promotionMove=m;showPromotion();}else move(m);return}if(p?.c===S.turn){select(r,c);return}S.selected=null;S.moves=[];render();return}if(p?.c===S.turn)select(r,c)}
function move(m){undo.push(clone(S));let p=S.b[m.from.r][m.from.c],capt=m.capture;if(capt)S.captured[p.c].push(capt);S.b=apply(S.b,m);S.ep=m.double?{r:(m.from.r+m.to.r)/2,c:m.from.c}:null;if(p.t==='k'){S.cast[p.c]={k:false,q:false}}if(p.t==='r'){if(m.from.c===0)S.cast[p.c].q=false;if(m.from.c===7)S.cast[p.c].k=false}if(m.castle)S.cast[p.c]={k:false,q:false};S.history.push(notation(m,p));S.turn=enemy(S.turn);S.selected=null;S.moves=[];S.positions[key(S.b)]=(S.positions[key(S.b)]||0)+1;finish();render()}
function notation(m,p){if(m.castle)return m.castle==='k'?'O-O':'O-O-O';let d=files[m.to.c]+(8-m.to.r),s=p.t==='p'?(m.capture?files[m.from.c]+'x':''):(p.t.toUpperCase()+(m.capture?'x':''));return s+d}
function finish(){let moves=allLegal(S.turn);if(!moves.length)S.over=inCheck(S.b,S.turn)?(S.turn==='w'?'CHECKMATE — Black wins!':'CHECKMATE — White wins!'):'DRAW — STALEMATE';else if(inCheck(S.b,S.turn))S.over=null;else if(Object.values(S.positions).some(n=>n>=3))S.over='DRAW — THREEFOLD REPETITION';else if(insufficient())S.over='DRAW — INSUFFICIENT MATERIAL'}function insufficient(){let p=S.b.flat().filter(x=>x&&x.t!=='k');return p.length===0||(p.length===1&&'bn'.includes(p[0].t))}
function render(){let board=document.querySelector('#board');board.innerHTML='<div class="label"></div>'+[0,1,2,3,4,5,6,7].map(c=>`<div class="label">${files[flipped?7-c:c].toUpperCase()}</div>`).join('');let rows=flipped?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7],cols=flipped?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7];for(let r of rows){board.innerHTML+=`<div class="label">${8-r}</div>`;for(let c of cols){let p=S.b[r][c],sel=S.selected?.r===r&&S.selected?.c===c,m=S.moves.find(x=>x.to.r===r&&x.to.c===c),cl=`square ${(r+c)%2?'dark':'light'} ${sel?'selected ':''}${m?(m.capture?'capture':'legal'):''}`;board.innerHTML+=`<button class="${cl}" data-r="${r}" data-c="${c}" aria-label="${files[c]}${8-r}">${p?`<span class="piece">${U[p.c][p.t]}</span>`:''}</button>`}}document.querySelectorAll('.square').forEach(x=>x.onclick=()=>click(+x.dataset.r,+x.dataset.c));document.querySelector('#turn').textContent=S.turn==='w'?'White':'Black';let st=document.querySelector('#status');st.textContent=S.over||(`${S.turn==='w'?'White':'Black'}${inCheck(S.b,S.turn)?' King is in Check':'\'s Turn'}`);st.parentElement.className='status panel '+(S.over?'end':inCheck(S.b,S.turn)?'check':'');document.querySelector('#whiteCaptured').textContent=S.captured.w.map(p=>U[p.c][p.t]).join(' ');document.querySelector('#blackCaptured').textContent=S.captured.b.map(p=>U[p.c][p.t]).join(' ');let h=document.querySelector('#history');h.innerHTML='';for(let i=0;i<S.history.length;i+=2)h.innerHTML+=`<div class="move"><span>${i/2+1}.</span><span>${S.history[i]||''}</span><span>${S.history[i+1]||''}</span></div>`}
function showPromotion(){let box=document.querySelector('#promotionChoices');box.innerHTML=['q','r','b','n'].map(t=>`<button data-t="${t}">${U[S.turn][t]} ${t.toUpperCase()}</button>`).join('');document.querySelector('#promotion').classList.remove('hidden');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{let m=promotionMove;m.promote=b.dataset.t;promotionMove=null;document.querySelector('#promotion').classList.add('hidden');move(m)})}
document.querySelector('#newGame').onclick=setup;document.querySelector('#undo').onclick=()=>{if(undo.length){S=undo.pop();render()}};document.querySelector('#flip').onclick=()=>{flipped=!flipped;render()};setup();
